// Mocks generated by Mockito 5.4.6 from annotations
// in personal_color_app/test/unit/features/camera/presentation/providers/camera_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:personal_color_app/core/error/failures.dart' as _i5;
import 'package:personal_color_app/core/usecases/usecase.dart' as _i6;
import 'package:personal_color_app/features/camera/domain/entities/camera_image.dart'
    as _i8;
import 'package:personal_color_app/features/camera/domain/entities/camera_permission.dart'
    as _i12;
import 'package:personal_color_app/features/camera/domain/entities/processed_image.dart'
    as _i10;
import 'package:personal_color_app/features/camera/domain/repositories/camera_repository.dart'
    as _i11;
import 'package:personal_color_app/features/camera/domain/usecases/initialize_camera.dart'
    as _i3;
import 'package:personal_color_app/features/camera/domain/usecases/process_image.dart'
    as _i9;
import 'package:personal_color_app/features/camera/domain/usecases/take_picture.dart'
    as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [InitializeCamera].
///
/// See the documentation for Mockito's code generation for more information.
class MockInitializeCamera extends _i1.Mock implements _i3.InitializeCamera {
  MockInitializeCamera() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> call(_i6.NoParams? params) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
              _FakeEither_0<_i5.Failure, void>(
                this,
                Invocation.method(#call, [params]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, void>>);
}

/// A class which mocks [TakePicture].
///
/// See the documentation for Mockito's code generation for more information.
class MockTakePicture extends _i1.Mock implements _i7.TakePicture {
  MockTakePicture() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i8.CameraImage>> call(
    _i6.NoParams? params,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i8.CameraImage>>.value(
                  _FakeEither_0<_i5.Failure, _i8.CameraImage>(
                    this,
                    Invocation.method(#call, [params]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i8.CameraImage>>);
}

/// A class which mocks [ProcessImage].
///
/// See the documentation for Mockito's code generation for more information.
class MockProcessImage extends _i1.Mock implements _i9.ProcessImage {
  MockProcessImage() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i10.ProcessedImage>> call(
    _i9.ProcessImageParams? params,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i10.ProcessedImage>>.value(
                  _FakeEither_0<_i5.Failure, _i10.ProcessedImage>(
                    this,
                    Invocation.method(#call, [params]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i10.ProcessedImage>>);
}

/// A class which mocks [CameraRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCameraRepository extends _i1.Mock implements _i11.CameraRepository {
  MockCameraRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isPreviewAvailable =>
      (super.noSuchMethod(
            Invocation.getter(#isPreviewAvailable),
            returnValue: false,
          )
          as bool);

  @override
  bool get isInitialized =>
      (super.noSuchMethod(Invocation.getter(#isInitialized), returnValue: false)
          as bool);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i12.CameraPermission>>
  getCameraPermission() =>
      (super.noSuchMethod(
            Invocation.method(#getCameraPermission, []),
            returnValue:
                _i4.Future<
                  _i2.Either<_i5.Failure, _i12.CameraPermission>
                >.value(
                  _FakeEither_0<_i5.Failure, _i12.CameraPermission>(
                    this,
                    Invocation.method(#getCameraPermission, []),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i12.CameraPermission>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i12.CameraPermission>>
  requestCameraPermission() =>
      (super.noSuchMethod(
            Invocation.method(#requestCameraPermission, []),
            returnValue:
                _i4.Future<
                  _i2.Either<_i5.Failure, _i12.CameraPermission>
                >.value(
                  _FakeEither_0<_i5.Failure, _i12.CameraPermission>(
                    this,
                    Invocation.method(#requestCameraPermission, []),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i12.CameraPermission>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, bool>> isCameraAvailable() =>
      (super.noSuchMethod(
            Invocation.method(#isCameraAvailable, []),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, bool>>.value(
              _FakeEither_0<_i5.Failure, bool>(
                this,
                Invocation.method(#isCameraAvailable, []),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, bool>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> initializeCamera() =>
      (super.noSuchMethod(
            Invocation.method(#initializeCamera, []),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
              _FakeEither_0<_i5.Failure, void>(
                this,
                Invocation.method(#initializeCamera, []),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i8.CameraImage>> takePicture() =>
      (super.noSuchMethod(
            Invocation.method(#takePicture, []),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i8.CameraImage>>.value(
                  _FakeEither_0<_i5.Failure, _i8.CameraImage>(
                    this,
                    Invocation.method(#takePicture, []),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i8.CameraImage>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> disposeCamera() =>
      (super.noSuchMethod(
            Invocation.method(#disposeCamera, []),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
              _FakeEither_0<_i5.Failure, void>(
                this,
                Invocation.method(#disposeCamera, []),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> optimizeMemoryUsage() =>
      (super.noSuchMethod(
            Invocation.method(#optimizeMemoryUsage, []),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
              _FakeEither_0<_i5.Failure, void>(
                this,
                Invocation.method(#optimizeMemoryUsage, []),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, void>>);
}
