// Mocks generated by Mockito 5.4.6 from annotations
// in personal_color_app/test/blocs/ai_fashion_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:io' as _i6;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i4;
import 'package:personal_color_app/models/ai_fashion_models.dart' as _i2;
import 'package:personal_color_app/repositories/ai_fashion_repository.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDuration_0 extends _i1.SmartFake implements Duration {
  _FakeDuration_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAICoordinateRecommendationResponseModel_1 extends _i1.SmartFake
    implements _i2.AICoordinateRecommendationResponseModel {
  _FakeAICoordinateRecommendationResponseModel_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(parent, parentInvocation);
}

/// A class which mocks [AIFashionRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAIFashionRepository extends _i1.Mock
    implements _i3.AIFashionRepository {
  MockAIFashionRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get baseUrl =>
      (super.noSuchMethod(
            Invocation.getter(#baseUrl),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#baseUrl),
            ),
          )
          as String);

  @override
  Duration get timeout =>
      (super.noSuchMethod(
            Invocation.getter(#timeout),
            returnValue: _FakeDuration_0(this, Invocation.getter(#timeout)),
          )
          as Duration);

  @override
  _i5.Future<_i2.AICoordinateRecommendationResponseModel>
  generateCoordinateRecommendation({
    required _i6.File? imageFile,
    required String? personalColorType,
    String? stylePreference,
    String? season,
    bool? includeAccessories = true,
    bool? generateImage = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#generateCoordinateRecommendation, [], {
              #imageFile: imageFile,
              #personalColorType: personalColorType,
              #stylePreference: stylePreference,
              #season: season,
              #includeAccessories: includeAccessories,
              #generateImage: generateImage,
            }),
            returnValue:
                _i5.Future<_i2.AICoordinateRecommendationResponseModel>.value(
                  _FakeAICoordinateRecommendationResponseModel_1(
                    this,
                    Invocation.method(#generateCoordinateRecommendation, [], {
                      #imageFile: imageFile,
                      #personalColorType: personalColorType,
                      #stylePreference: stylePreference,
                      #season: season,
                      #includeAccessories: includeAccessories,
                      #generateImage: generateImage,
                    }),
                  ),
                ),
          )
          as _i5.Future<_i2.AICoordinateRecommendationResponseModel>);

  @override
  _i5.Future<bool> checkAPIHealth() =>
      (super.noSuchMethod(
            Invocation.method(#checkAPIHealth, []),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);
}
