// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5O0mah5HjwWsUVfku65aE8FfPWQxpxPY',
    appId: '1:666814602151:ios:5f32e71d7586ae0c1ff482',
    messagingSenderId: '666814602151',
    projectId: 'personal-color-469007',
    storageBucket: 'personal-color-469007.firebasestorage.app',
    iosBundleId: 'com.personalcolor.diagnosisapp.RunnerTests',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJzVabmhzl8rwSvWYnz8UTiLnnrc0NEdU',
    appId: '1:666814602151:android:41bc2980717457781ff482',
    messagingSenderId: '666814602151',
    projectId: 'personal-color-469007',
    storageBucket: 'personal-color-469007.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5O0mah5HjwWsUVfku65aE8FfPWQxpxPY',
    appId: '1:666814602151:web:web-app-id-placeholder',
    messagingSenderId: '666814602151',
    projectId: 'personal-color-469007',
    authDomain: 'personal-color-469007.firebaseapp.com',
    storageBucket: 'personal-color-469007.firebasestorage.app',
    measurementId: 'G-measurement-id-placeholder',
  );

}