// Mocks generated by Mockito 5.4.6 from annotations
// in personal_color_app/test/features/clothing/integration/clothing_integration_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:personal_color_app/features/clothing/data/datasources/clothing_remote_data_source.dart'
    as _i3;
import 'package:personal_color_app/features/clothing/data/models/clothing_recommendation_model.dart'
    as _i2;
import 'package:personal_color_app/features/diagnosis/domain/entities/diagnosis_result.dart'
    as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeClothingRecommendationModel_0 extends _i1.SmartFake
    implements _i2.ClothingRecommendationModel {
  _FakeClothingRecommendationModel_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ClothingRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockClothingRemoteDataSource extends _i1.Mock
    implements _i3.ClothingRemoteDataSource {
  MockClothingRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.ClothingRecommendationModel> getClothingRecommendations(
    _i5.PersonalColorType? personalColorType,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getClothingRecommendations, [personalColorType]),
            returnValue: _i4.Future<_i2.ClothingRecommendationModel>.value(
              _FakeClothingRecommendationModel_0(
                this,
                Invocation.method(#getClothingRecommendations, [
                  personalColorType,
                ]),
              ),
            ),
          )
          as _i4.Future<_i2.ClothingRecommendationModel>);

  @override
  _i4.Future<List<Map<String, dynamic>>> getProductsByCategory(
    _i5.PersonalColorType? personalColorType,
    String? category,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getProductsByCategory, [
              personalColorType,
              category,
            ]),
            returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i4.Future<List<Map<String, dynamic>>>);

  @override
  _i4.Future<Map<String, dynamic>> checkApiHealth() =>
      (super.noSuchMethod(
            Invocation.method(#checkApiHealth, []),
            returnValue: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i4.Future<Map<String, dynamic>>);
}
