// Mocks generated by Mockito 5.4.6 from annotations
// in personal_color_app/test/features/diagnosis/domain/usecases/diagnose_personal_color_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:personal_color_app/core/error/failures.dart' as _i5;
import 'package:personal_color_app/features/diagnosis/domain/entities/diagnosis_request.dart'
    as _i7;
import 'package:personal_color_app/features/diagnosis/domain/entities/diagnosis_result.dart'
    as _i6;
import 'package:personal_color_app/features/diagnosis/domain/repositories/diagnosis_repository.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [DiagnosisRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockDiagnosisRepository extends _i1.Mock
    implements _i3.DiagnosisRepository {
  MockDiagnosisRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.DiagnosisResult>> diagnosePerson(
    _i7.DiagnosisRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#diagnosePerson, [request]),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i6.DiagnosisResult>>.value(
                  _FakeEither_0<_i5.Failure, _i6.DiagnosisResult>(
                    this,
                    Invocation.method(#diagnosePerson, [request]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.DiagnosisResult>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.DiagnosisResult>>
  diagnosePersonalColorEnhanced(_i7.DiagnosisRequest? request) =>
      (super.noSuchMethod(
            Invocation.method(#diagnosePersonalColorEnhanced, [request]),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i6.DiagnosisResult>>.value(
                  _FakeEither_0<_i5.Failure, _i6.DiagnosisResult>(
                    this,
                    Invocation.method(#diagnosePersonalColorEnhanced, [
                      request,
                    ]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.DiagnosisResult>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, bool>> checkApiHealth() =>
      (super.noSuchMethod(
            Invocation.method(#checkApiHealth, []),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, bool>>.value(
              _FakeEither_0<_i5.Failure, bool>(
                this,
                Invocation.method(#checkApiHealth, []),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, bool>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, Map<String, dynamic>>> testConnection() =>
      (super.noSuchMethod(
            Invocation.method(#testConnection, []),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, Map<String, dynamic>>>.value(
                  _FakeEither_0<_i5.Failure, Map<String, dynamic>>(
                    this,
                    Invocation.method(#testConnection, []),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, Map<String, dynamic>>>);
}
