// Mocks generated by Mockito 5.4.6 from annotations
// in personal_color_app/test/features/clothing/domain/usecases/get_clothing_recommendations_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:personal_color_app/core/errors/failures.dart' as _i5;
import 'package:personal_color_app/features/clothing/domain/entities/clothing_product.dart'
    as _i8;
import 'package:personal_color_app/features/clothing/domain/entities/clothing_recommendation.dart'
    as _i6;
import 'package:personal_color_app/features/clothing/domain/repositories/clothing_repository.dart'
    as _i3;
import 'package:personal_color_app/features/diagnosis/domain/entities/diagnosis_result.dart'
    as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ClothingRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockClothingRepository extends _i1.Mock
    implements _i3.ClothingRepository {
  MockClothingRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.ClothingRecommendation>>
  getClothingRecommendations(
    _i7.PersonalColorType? personalColorType, {
    bool? forceRefresh = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getClothingRecommendations,
              [personalColorType],
              {#forceRefresh: forceRefresh},
            ),
            returnValue:
                _i4.Future<
                  _i2.Either<_i5.Failure, _i6.ClothingRecommendation>
                >.value(
                  _FakeEither_0<_i5.Failure, _i6.ClothingRecommendation>(
                    this,
                    Invocation.method(
                      #getClothingRecommendations,
                      [personalColorType],
                      {#forceRefresh: forceRefresh},
                    ),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.ClothingRecommendation>>);

  @override
  _i4.Future<bool> clearCache() =>
      (super.noSuchMethod(
            Invocation.method(#clearCache, []),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> hasCachedData(_i7.PersonalColorType? personalColorType) =>
      (super.noSuchMethod(
            Invocation.method(#hasCachedData, [personalColorType]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<DateTime?> getLastCacheUpdateTime(
    _i7.PersonalColorType? personalColorType,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getLastCacheUpdateTime, [personalColorType]),
            returnValue: _i4.Future<DateTime?>.value(),
          )
          as _i4.Future<DateTime?>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i8.ClothingProduct>>>
  getProductsByCategory(
    _i7.PersonalColorType? personalColorType,
    _i8.ClothingCategory? category,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getProductsByCategory, [
              personalColorType,
              category,
            ]),
            returnValue:
                _i4.Future<
                  _i2.Either<_i5.Failure, List<_i8.ClothingProduct>>
                >.value(
                  _FakeEither_0<_i5.Failure, List<_i8.ClothingProduct>>(
                    this,
                    Invocation.method(#getProductsByCategory, [
                      personalColorType,
                      category,
                    ]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i8.ClothingProduct>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, Map<String, dynamic>>>
  getRecommendationStats(_i7.PersonalColorType? personalColorType) =>
      (super.noSuchMethod(
            Invocation.method(#getRecommendationStats, [personalColorType]),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, Map<String, dynamic>>>.value(
                  _FakeEither_0<_i5.Failure, Map<String, dynamic>>(
                    this,
                    Invocation.method(#getRecommendationStats, [
                      personalColorType,
                    ]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, Map<String, dynamic>>>);
}
